name: rl_algo_impls
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10.*
  - mamba
  - pip
  - poetry
  - pytorch
  - torchvision
  - torchaudio
  - cmake
  - swig
  - ipywidgets
  - black
